export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const GET_PLAY_LIST = 'GET_PLAY_LIST';
export const VERIFY_ADMIN_SUCCESS = 'VERIFY_ADMIN_SUCCESS';
export const POST_LIST_ITEM = 'POST_LIST_ITEM';
export const UPDATE_LIST_ITEM = 'UPDATE_LIST_ITEM';
export const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';

export const GET_ACCOUNTS_HISTORY = 'GET_ACCOUNTS_HISTORY';
export const SET_COMPLEXITY = 'SET_COMPLEXITY';
export const TOGGLE_SEARCH_BTN = 'TOGGLE_SEARCH_BTN';
export const TOGGLE_CLEAR_BTN = 'TOGGLE_CLEAR_BTN';
export const CHANGE_INPUT_SEARCH_BLOCK = 'CHANGE_INPUT_SEARCH_BLOCK';
export const CLEAR_INPUT_SEARCH_BLOCK = 'CLEAR_INPUT_SEARCH_BLOCK';
export const SEARCH_BLOCK_ERROR = 'SEARCH_BLOCK_ERROR';
export const SEARCH_BLOCK_SUCCESS = 'SEARCH_BLOCK_SUCCESS';

export const SHOW_TOKEN_BALANCE = 'SHOW_TOKEN_BALANCE';
export const GET_DOM_TABLE_DATA = 'GET_DOM_TABLE_DATA';
export const GET_LOGIN_HISTORY = 'GET_LOGIN_HISTORY';
export const GET_ACTION_HISTORY = 'GET_ACTION_HISTORY';

export const GET_CANDLESTICK_CHART_DATA = 'GET_CANDLESTICK_CHART_DATA';
export const SET_TODAY_STATUS = 'SET_TODAY_STATUS';
export const SET_OFFSET_NUMBER = 'SET_OFFSET_NUMBER';
export const HIDE_LOAD_MORE_BUTTON = 'HIDE_LOAD_MORE_BUTTON';
export const SET_MINUTE_INTERVAL = 'SET_MINUTE_INTERVAL';
export const SET_HOUR_INTERVAL = 'SET_HOUR_INTERVAL';
export const SET_WEEK_INTERVAL = 'SET_WEEK_INTERVAL';
export const GET_MINI_CHART_DATA = 'GET_MINI_CHART_DATA';
export const SET_DATE_FILTER = 'SET_DATE_FILTER';
export const SET_PAIR_FILTER = 'SET_PAIR_FILTER';
export const SET_DEFAULT_PAIR_FILTER = 'SET_DEFAULT_PAIR_FILTER';
export const SET_SIDE_FILTER = 'SET_SIDE_FILTER';
export const SET_HIDE_CANCELEDE_CHECKBOX_STATE = 'SET_HIDE_CANCELEDE_CHECKBOX_STATE';

